=begin
  Yunejian的Podfile....
  YY开头的是YYSpecs项目私有库
=end

source 'https://github.com/CocoaPods/Specs.git' #引入pod原有的私有库     
source 'https://git.ycosystem.com/iOSMode/YYSpecs.git' #引入自定义私有库   

platform :ios,’8.0’
target 'Yunejian' do

 pod 'YYToast', '~> 0.1.1' # 三端通用toast

 pod 'MBProgressHUD', '~> 1.0.0'
 pod 'AFNetworking', '~> 2.5.4'
 pod 'SDWebImage', '~> 3.8.2’
 pod 'JSONModel', '~> 1.2.0'
 pod 'MJExtension', '~>3.0.13'
 pod 'Masonry', '~> 0.6.4'
 pod 'Qiniu', '~> 7.0.16'
 pod 'TTTAttributedLabel', '~> 1.13.4'
 pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5' # 无 idfa版本
 pod 'Bugly', '~> 2.4.8'
 pod 'MJRefresh', '~> 3.1.12'
 pod 'RealReachability', '~> 1.1.9'

end
